version: '3.3'
services:
  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_PASSWORD=biosignal-auth
      - POSTGRES_USER=biosignal-auth
      - POSTGRES_DB=biosignal-auth
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: /bin/sh -c "orator migrate --config /app/config.py -f && python /app/webapp.py"
    environment:
      - POSTGRES_PASSWORD=biosignal-auth
      - POSTGRES_USER=biosignal-auth
      - POSTGRES_DB=biosignal-auth
      - POSTGRES_HOST=db
      - SECRET_KEY_BASE=f187418a8f99847aa66912dfb87f9c865fdb5a628475a507393c2fed4d810593fd127cbd293a23088c9144e15dc9742ba17e158963f41b0b8fde7a73926d42b9
    volumes:
      - .:/app
    ports:
      - 5000:5000
    networks:
      - default
    depends_on:
      - db

networks:
  default:
volumes:
  db-data:
